version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - run:
          name: Install build dependencies
          command: |
            apt-get -qq update
            apt-get -qy install ca-certificates libpoco-dev libleveldb-dev git-core cmake build-essential libboost-regex-dev libboost-filesystem-dev libboost-test-dev libboost-system-dev libboost-program-options-dev libz3-dev
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - build-{{ checksum "CMakeLists.txt" }}
      - run:
          name: Fix host authenticity for github.com
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
            make
      - save_cache:
          name: Save cache
          key: build-{{ checksum "CMakeLists.txt" }}
          paths:
            - ~/.hunter
            - build/cpp-ethereum-git
            - build/solidity-git
      - store_artifacts:
          path: build/soltest/soltest
          destination: soltest
      - persist_to_workspace:
          root: build
          paths:
            - soltest/soltest
            - test/soltest-unittests
